### ISSUE TITLE
请问如果想自定义一个域名走代理，应该怎么设置呢？

### ISSUE THREAD

**Issue by Woodblocks** [RealSeek/Clash_Rule_DIY#2]
如题，谢谢

**Comment by RealSeek** [comment]
其实如果你实在不会 你可以在 issues 内提供需要 走代理 或 不走代理 的域名，我看到后都会加进去

如果你要自己添加的话，在 PROXY 内找一个配置文件自行填入匹配类型和域名即可

**Comment by Woodblocks** [comment]
谢谢楼主，已经找到了一个配置加进去了。我是想添加：https://poe.com/

供参考，谢谢。

**Comment by RealSeek** [comment]
已在配置文件内添加
