### ISSUE TITLE
还是不知道怎么使用

### ISSUE THREAD

**Issue by anjue39** [RealSeek/Clash_Rule_DIY#3]
还是不知道怎么使用，能不能提供一个具体的clash的规则yml格式

**Comment by RealSeek** [comment]
具体看 [Parsers 预处理文件配置案例](https://github.com/RealSeek/Clash_Rule_DIY/blob/master/README.md#parsers-%E9%A2%84%E5%A4%84%E7%90%86%E6%96%87%E4%BB%B6%E9%85%8D%E7%BD%AE%E6%A1%88%E4%BE%8B)
